version: "3"

services:

  configserver:
    image: ggingmin/configserver:latest
    ports:
      - "8071:8071"
    networks:
      - ggingbank-network

  eurekaserver:
    image: ggingmin/eurekaserver:latest
    ports:
      - "8070:8070"
    networks:
      - ggingbank-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 60s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  accounts:
    image: ggingmin/accounts:latest
    ports:
      - "8080:8080"
    networks:
      - ggingbank-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 8s
        max_attempts: 3
        window: 60s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  loans:
    image: ggingmin/loans:latest
    ports:
      - "8090:8090"
    networks:
      - ggingbank-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 8s
        max_attempts: 3
        window: 60s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  cards:
    image: ggingmin/cards:latest
    ports:
      - "9000:9000"
    networks:
      - ggingbank-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 8s
        max_attempts: 3
        window: 60s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

networks:
  ggingbank-network: